name: Update IPTV

on:
  workflow_dispatch:
  push:
    paths:
      - 'iptv.py'
      - '.github/workflows/main.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: 运行 IPTV 抓取脚本
        run: python iptv.py

      - name: 上传生成的 M3U 文件
        uses: actions/upload-artifact@v4
        with:
          name: live_list-m3u
          path: live_list.m3u

      - name: 上传生成的 TXT 文件
        uses: actions/upload-artifact@v4
        with:
          name: live_list-txt
          path: live_list.txt
